//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Web-File-Explorer.rc 使用
//
#define IDR_MENU_MAINAPP                1202
#define IDR_ACCELERATOR_MAINAPP         1203
#define IDS_STRING_APP_UUID             1301
#define IDS_STRING_APP_GUID             1302
#define IDS_STRING_WEBEXPACK_DOWNLOAD   1303
#define IDS_STRING_UI_CLASS_MAIN        1353
#define IDS_STRING_UI_TITLE_MAIN        1354
#define IDS_STRING_UI_CLASS_CREDIT      1355
#define ID_MENU_FILE_NEW                40001
#define ID_MENU_FILE_OPENSERVER         40002
#define ID_MENU_FILE_OPENFILE           40003
#define ID_MENU_FILE_SAVESERVERCONFIG   40004
#define ID_MENU_FILE_SAVEAS             40005
#define ID_MENU_FILE_RECENT             40006
#define ID_MENU_FILE_CLOSE              40007
#define ID_MENU_FILE_EXIT               40008
#define ID_MENU_EDIT_GO                 40009
#define ID_MENU_EDIT_FINDREPLACE        40010
#define ID_MENU_FINDREPLACE_FIND        40011
#define ID_MENU_FINDREPLACE_REPLACE     40012
#define ID_MENU_EDIT_UNDO               40013
#define ID_MENU_EDIT_REDO               40014
#define ID_MENU_EDIT_CUT                40015
#define ID_MENU_EDIT_COPY               40016
#define ID_MENU_EDIT_PASTE              40017
#define ID_MENU_EDIT_DELETE             40018
#define ID_MENU_EDIT_SELECTALL          40019
#define ID_MENU_VIEW_MAINWINDOW         40020
#define ID_MENU_VIEW_ALPHA              40021
#define ID_MENU_WINDOW_WINDOWOPTIONS    40022
#define ID_MENU_WINDOWOPTIONS_NOOPTIONAVAILABLE 40023
#define ID_MENU_SERVER_SERVEROPTIONS    40024
#define ID_MENU_WINDOW_SHOWNORMAL       40025
#define ID_MENU_WINDOW_MINIMIZE         40026
#define ID_MENU_WINDOW_MAXIMIZE         40027
#define ID_MENU_WINDOW_CLOSEWINDOW      40028
#define ID_MENU_WINDOW_TASKBARICON      40029
#define ID_MENU_SERVER_SERVERDATA       40030
#define ID_MENU_SERVERDATA_SERVERADDRESS 40031
#define ID_MENU_SERVERDATA_SERVERPORT   40032
#define ID_MENU_SERVER_STARTSERVER      40033
#define ID_MENU_SERVER_STOPSERVER       40034
#define ID_MENU_TOOL_COMMANDPROMOT      40035
#define ID_MENU_HELP_HELPTOPIC          40036
#define ID_MENU_HELP_GETHELP            40037
#define ID_MENU_HELP_KEYBOARDSHORTCUTREFERENCE 40038
#define ID_MENU_HELP_FEEDBACK           40039
#define ID_MENU_FEEDBACK_SENDABUGREPORT 40040
#define ID_MENU_FEEDBACK_SENDA          40041
#define ID_MENU_FEEDBACK_OTHERFEEDBACK  40042
#define ID_MENU_HELP_CHECKFORUPDATES    40043
#define ID_MENU_HELP_AUTOUPDATE         40044
#define ID_MENU_AUTOUPDATE_ENABLEAUTOUPDATE 40045
#define ID_MENU_AUTOUPDATE_AUTOUPDATEOPTIONS 40046
#define ID_MENU_HELP_UPDATEROPTIONS     40047
#define ID_MENU_HELP_TERMSOFSERVICE     40048
#define ID_MENU_HELP_PRIVACYPOLICY      40049
#define ID_MENU_HELP_ABOUT              40050
#define ID_MENU_SERVER_OPENSERVER       40051
#define ID_MENU_SERVER_OPENSERVERWITHTOKEN 40052
#define ID_MENU_SERVER_OPENSERVERWITHCREDENTIALS 40053
#define ID_MENU_NEW_NEWWINDOW           40054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40067
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
