blank_issues_enabled: true
contact_links:
  - name: General Questions
    url: https://github.com/winsiderss/systeminformer/discussions/new
    about: Have a question? Start a new discussion instead of open an issue.
  - name: Create a blank issue
    url: https://github.com/shc0743/Web-File-Explorer/issues/new
    about: Create a blank issue for anything else.
